apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-deployment-1
spec:
  replicas: 10
  selector:
    matchLabels:
      app: hello-kubernetes
      environment: prod
      version: "1"
  template:
    metadata:
      labels:
        app: hello-kubernetes
        version: "1"
        environment: prod
    spec:
      containers:
      - name: hellokubernetes
        image: lukasslizik/hellokubernetes:1.0
        ports:
        - containerPort: 8080