apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world1-deployment
  labels:
    app: hello-world
    version: v1
    environment: production
spec:
  replicas: 25
  selector:
    matchLabels:
      app: hello-world
      version: v1
      environment: production
  template:
    metadata:
      labels:
        app: hello-world
        version: v1
        environment: production
    spec:
      containers:
      - name: hello-world1
        image: lukasslizik/hello-world1
        ports:
        - containerPort: 8080