apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world1-deployment
  labels:
    app: hello-world1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world1
  template:
    metadata:
      labels:
        app: hello-world1
    spec:
      containers:
      - name: hello-world1
        image: lukasslizik/hello-world1
        ports:
        - containerPort: 3000