apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world2-deployment
  labels:
    app: hello-world
    version: v2
    environment: production
spec:
  replicas: 10
  selector:
    matchLabels:
      app: hello-world
      version: v2
      environment: production
  template:
    metadata:
      labels:
        app: hello-world
        version: v2
        environment: production
    spec:
      containers:
      - name: hello-world2
        image: lukasslizik/hello-world2
        ports:
        - containerPort: 8080