apiVersion: v1
kind: Service
metadata:
  name: first-service
spec:
  type: NodePort
  selector:
    app: nodejs-hello-world1
  ports:
    - protocol: TCP
      nodePort: 32760
      port: 3000
      name: http
      targetPort: 3000