apiVersion: v1
kind: Service
metadata:
  name: first-service
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "least_connections"
spec:
  type: LoadBalancer
  selector:
    app: hello-world
    environment: production
  ports:
    - protocol: TCP
      nodePort: 32760
      port: 8080
      name: http
      targetPort: 8080
  