apiVersion: v1
kind: Service
metadata:
  name: first-service
spec:
  type: LoadBalancer
  selector:
    run: first-pod
  ports:
    - protocol: TCP
      nodePort: 32760
      port: 3000
      name: http
      targetPort: 80