apiVersion: v1
kind: Pod
metadata:
  name: hello-world1
  labels:
    app: hello-world1
spec:
  containers:
  - name: hello-world1
    image: lukasslizik/hello-world1
    resources:
      limits:
        cpu: "1"
        memory: "200Mi"
    ports:
    - containerPort: 8080