apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    run: first-pod
spec:
  containers:
  - name: nodejs-hello-world
    image: heroku/nodejs-hello-world
    resources:
      limits:
        cpu: "1"
        memory: "200Mi"
    ports:
    - containerPort: 3000

# https://kubernetes.io/docs/tutorials/stateless-application/expose-external-ip-address/