apiVersion: v1
kind: Pod
metadata:
  name: hello-kubernetes
  labels:
    app: hello-kubernetes
    environment: prod
    version: "1"
spec:
  containers:
  - name: hello-kubernetes
    image: lukasslizik/hellokubernetes:1.0
    resources:
      limits:
        cpu: "1"
        memory: "200Mi"
    ports:
    - containerPort: 8080